In [11]:
import numpy as np
import random
import pandas as pd

In [12]:
# sprawdzanie poprawności dwóch strategii

def check_strategy(s1: list[int], s2: list[int]) -> bool:
    return (len(s1) == len(s2)) and (np.sum(s1) == 100) and (np.sum(s2) == 100)

In [13]:
# wykrywanie zwycięzcy gry - s1: nasza strategia, s2: przeciwnik
# True - wygrana, False - przegrana

def game_result(s1: list[int], s2: list[int]) -> bool:
    counter_player1 = 0
    counter_player2 = 0
    points_player1 = 0
    points_player2 = 0
    
    for i, j in zip(s1, s2):
        if (counter_player1 < 3) and (counter_player2 < 3):
            if i==j:
                points_player1 += 0.5
                points_player2 += 0.5
            elif i > j:
                points_player1 += 1
                counter_player1 += 1
            else: 
                points_player2 += 1
                counter_player2 += 1
        else:
            break
         
    if counter_player1 == 3:
        result = True
    elif counter_player2 == 3:
        result = False
    else: 
        if points_player1 > points_player2:
            result = True
        elif points_player1 < points_player2:
            result = False
        else:
            result = False
            
    return result

In [14]:
# generowanie n strategi wg opisanych zasad losowania
def random_strategies(num: int) -> list:
    
    all_strategies = []
    for i in range(num):
        strategy = []
        total_soldiers = 100
        for i in range(1,10):
            val = random.randint(0, total_soldiers)
            total_soldiers -= val
            strategy.append(val)
            
        strategy.append(total_soldiers)
        
        if (len(strategy) == 10) and (np.sum(strategy) == 100):
            all_strategies.append(strategy)
    return all_strategies

# generowanie 1000 strategi - pokazuję pierwsze 10
random_strategies(1000)[:10]

[[82, 18, 0, 0, 0, 0, 0, 0, 0, 0],
 [99, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [68, 32, 0, 0, 0, 0, 0, 0, 0, 0],
 [42, 44, 7, 3, 2, 0, 2, 0, 0, 0],
 [71, 6, 12, 1, 2, 4, 4, 0, 0, 0],
 [99, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [14, 66, 16, 3, 1, 0, 0, 0, 0, 0],
 [99, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [98, 2, 0, 0, 0, 0, 0, 0, 0, 0],
 [4, 15, 37, 40, 2, 1, 0, 1, 0, 0]]

In [15]:
# zamiana typu danych w celu przepowadzenia analizy

def transform_into_dataframe(data: list) -> pd.DataFrame:
    df = {f"bf{i+1}": [j[i] for j in data] for i in range(0,10)}
    return pd.DataFrame(df)

In [16]:
# generowanie 1 mln strategi i budowa dataframe'u

strategies =  random_strategies(1000000)
data = transform_into_dataframe(strategies)

data.head(15)

    bf1  bf2  bf3  bf4  bf5  bf6  bf7  bf8  bf9  bf10
0    80    5    7    8    0    0    0    0    0     0
1    49   17    3    5    4    5   12    2    3     0
2    32   12   37   13    2    0    1    2    0     1
3    97    3    0    0    0    0    0    0    0     0
4    41   15    4   13   11   15    0    1    0     0
5    60    3   11   11    7    8    0    0    0     0
6    76    0   16    7    0    0    0    1    0     0
7    42   28   15    0   10    3    0    2    0     0
8    53   29    5    2    5    6    0    0    0     0
9    60    8   23    4    3    2    0    0    0     0
10   71   21    5    2    0    1    0    0    0     0
11   73    3   11    1   12    0    0    0    0     0
12   46    8   35    0    5    5    1    0    0     0
13   69   25    2    0    1    3    0    0    0     0
14   69   15    7    4    0    1    3    0    0     1

In [17]:
# sprawdzenie średich wartości dla poszczególnych pól
print("Average values for columns: \n")
for col in data.columns:
    print(col, np.mean(data[col]))

Average values for columns:

bf1 50.003471
bf2 25.003171
bf3 12.485425
bf4 6.249267
bf5 3.133411
bf6 1.561575
bf7 0.782196
bf8 0.390106
bf9 0.195152
bf10 0.196226

In [18]:
# generowanie listy wyników ze wszyctkich gier i obliczenie win rate
def strategy_winrate(strategy: list[int], data: pd.DataFrame) -> float:
    all_results = []
    for index, row in data.iterrows():
        results = game_result(s1=strategy,
                              s2=[row["bf1"], row["bf2"], row["bf3"], row["bf4"], row["bf5"], row["bf6"], row["bf7"], row["bf8"], row["bf9"], row["bf10"]])
        all_results.append(results)
    win_rate = sum(all_results)/len(all_results)*100
    return round(win_rate, 2)

In [19]:
# testowanie dowolnej strategii
wins = strategy_winrate(strategy=[0, 0, 55, 30, 15, 0, 0, 0, 0, 0], data=data)

print("Strategy has:", wins, "% win rate")

Strategy has: 89.18 % win rate